# Generated by Django 5.1.7 on 2025-03-26 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MinecraftServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=16)),
                ("port", models.IntegerField()),
                ("motd", models.TextField()),
                ("version", models.CharField(max_length=64)),
                ("max_players", models.IntegerField()),
                ("online_mode", models.BooleanField()),
                ("core", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="MinecraftPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=32)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="app.minecraftserver",
                    ),
                ),
            ],
        ),
    ]
