# Generated by Django 5.1.7 on 2025-03-27 02:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="minecraftplayer",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="minecraftserver",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
