# Generated by Django 5.1.7 on 2025-03-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_minecraftplayer_timestamp_alter_minecraftserver_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="minecraftserver",
            name="ip",
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
