# Generated by Django 5.1.7 on 2025-03-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_minecraftserver_ip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="minecraftserver",
            name="core",
            field=models.CharField(default="Unknown", max_length=64),
        ),
    ]
