# Generated by Django 5.1.7 on 2025-03-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_minecraftserver_core"),
    ]

    operations = [
        migrations.AddField(
            model_name="minecraftplayer",
            name="online",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="minecraftplayer",
            name="nickname",
            field=models.CharField(max_length=16, null=True),
        ),
    ]
