# Generated by Django 5.1.7 on 2025-03-27 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_remove_minecraftplayer_server_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="minecraftplayer",
            name="online",
        ),
    ]
