# Generated by Django 5.1.7 on 2025-03-28 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_remove_minecraftplayer_online"),
    ]

    operations = [
        migrations.CreateModel(
            name="MinecraftServerOnline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("online", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.minecraftserver",
                    ),
                ),
            ],
        ),
    ]
