# Generated by Django 5.1.7 on 2025-03-28 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_minecraftserveronline"),
    ]

    operations = [
        migrations.CreateModel(
            name="MinecraftPlayerSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("join_time", models.DateTimeField(auto_now_add=True)),
                ("leave_time", models.DateTimeField(null=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.minecraftplayer",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.minecraftserver",
                    ),
                ),
            ],
        ),
    ]
